apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    owner: EmirD
spec:
  selector:
    project: {{ .Release.Name }}    # Selecting PODS with those Labels
  ports:
    - name      : {{ .Release.Name }}-listener
      port: 80
      targetPort: 3000
